### ISSUE TITLE
Sharing research

### ISSUE THREAD

**Issue by juliosantos** [Sevenzo/challenge-platform#157]
Note that this is a research piece only.

@masauzi10 @krnjn:
Re [your example](https://www.addup.org/campaigns/stop-food-waste-in-american-grocery-stores), could you be more specific in terms of why you like it? For me it's a bit overwhelming. Asking me to log into a site with Facebook, and give them my personal information, in order to share something, is a bit overkill and I'd wager it drops conversion rates.

Let me try this too: is the problem 1, 2, or both?
1. There's content (challenges, contributions, ...) which is not yet shareable in any way. Which content would you like to make shareable?
2. When you share something (like an "idea") on Facebook, the share message is generic and not specific to what you share.

Alternatively, could you be a bit more specific about what you'd like done here? What goal are you trying to achieve?

**Comment by masauzi10** [comment]
This is a discovery task to start. Given that we are able to leverage Twitter and FB APIs, I'd like to know the most interesting/supportive Twitter/FB leverage points given our design concept (see this mock up: https://projects.invisionapp.com/share/WS9GCKIRC#/screens/207445762)

Our goal is to build a visual representation of progress' we're making w/ our tactics, for example the mini challenges. See this as example https://www.addup.org/campaigns/tell-president-obama-to-protect-the-grand-canyon-heer

**Comment by juliosantos** [comment]
@masauzi10: the invision link you posted above is no longer working...

**Comment by juliosantos** [comment]
New link: https://projects.invisionapp.com/share/BE9UCRXV3#/screens

**Comment by juliosantos** [comment]
Here's the report: https://docs.google.com/document/d/1Gv7lZrBD0qAYU_38nM4OZ402E9IpzZzOhJ0zhbZcau8/edit?usp=sharing
