### ISSUE TITLE
Add other team members to the About Us Page

### ISSUE THREAD

**Issue by juliosantos** [Sevenzo/challenge-platform#159]
As per the description: Leslie Garner Franklin, Nicki Bosch, Julianne Canterbury, Michael Burdick, Stedman Hood

Notes from [Redesign Site_All Work](https://docs.google.com/document/d/1nV1Qrq5BCFAmwi7DrDPN6X6tiV90_nbmUoCp9b9YCvM/edit):
* Add contractors to the Our Team Section
  * Change Christina Esquivel’s title to: Program Engagement Manager 
  * Leslie Garner Franklin, Director, Program Design & Implementation
  * Yenssy Goyins, Marketing Manager
  * Julianne Canterbury, Social Media Manager
  * Michael Burdick, Operations Manager 
  * Stedman Hood, Developer 
  * Nicki Bosch, Strategic Partnerships & Events Manager
* Add Chris Roberts to below Advisor List [image here](https://drive.google.com/open?id=0BxGUjWgfzzWYWlVrR2ctc3R5azQ)
* Change Stephen Mueller Company name to Ascender (vs. Thrill Mill)

**Comment by juliosantos** [comment]
@karan says: @masauzi10: for everyone else's links (linkedIn, email, twitter) + bio (if they need / want one) + image before we finish this

**Comment by masauzi10** [comment]
I don't think we should add bios.Will take up too much space. So, linked in, email, twitter. Intel is in the google doc we were using a while ago. I liked your idea @krnjn about either centering my profile or just adding photos in row/columns
