### ISSUE TITLE
Video Splash

### ISSUE THREAD

**Issue by juliosantos** [Sevenzo/challenge-platform#164]
See sizzle video files

**Comment by juliosantos** [comment]
@masauzi10 says: Hey there. I think we're removing this from Queue, yes, because we're replacing it with files? @krnjn agreed?

**Comment by juliosantos** [comment]
@krnjn says: You mean the slider? I think we are still waiting to hear feedback? 

Here's my 2 c: slider is easier to get done from a technical standpoint and works better on mobile and is front and center - I don't think tabs are that intuitive for our audience.

It also brings up other content and doesn't disrupt most of the page, so yeah I think we can scrap the video header AND tabs (and instead put the content that was supposed to go in the tabs in the slider on the top element instead.)

**Comment by krnjn** [comment]
I think we'll be tabling this per @masauzi10's comment.

**Comment by masauzi10** [comment]
Not sure I understand what we mean by tabs? Do we mean Maria's design? If so, she's delivering an integrated version of that design for both desktop and mobile by EOD and we should make a decision based on that deliverable per our convo @krnjn
