### ISSUE TITLE
Challenge navigation

### ISSUE THREAD

**Issue by stedmanblake** [Sevenzo/challenge-platform#97]
- I get that this is challenging but I do think it is a decent improvement / worth it. Given that you’ve spent so much time on it, we should probably try to knock it out. I can review / give it a once over to make sure we’re on the right track.

**Comment by stedmanblake** [comment]
@krnjn just wanna confirm you're referring to the latest mockup from Chris (below) rather than the initial spec (which is complete, here: https://github.com/Sevenzo/challenge-platform/pull/96)
![image](https://cloud.githubusercontent.com/assets/4050144/19623087/c9d5aa92-9870-11e6-83fd-742ea800602a.png)

**Comment by krnjn** [comment]
@stedmanblake – yep, if that's the one from zeplin, then yeah that's what I was referring to. Will review it today.
